In [1]:
object_list <- ls()
print(object_list)

character(0)


In [3]:
# Create a variable called lvl that contains the following values:  8, 10, 10, 1, 10, 10, 8, 12, 1, 12.
lvl <- c(8, 10, 10, 1, 10, 10, 8, 12, 1, 12)
lvl

[1]  8 10 10  1 10 10  8 12  1 12

In [4]:
#Find the sum of the elements in lvl
sum_lvl <- sum(lvl)
print(sum_lvl)

[1] 82


In [5]:
#Find the average of the elements in lvl
avg_lvl <- mean(lvl)
print(avg_lvl)

[1] 8.2


In [6]:
#Find the median value (the middle value) of the elements in lvl
median_lvl <- median(lvl)
print(median_lvl)

[1] 10


In [7]:
#Get R to return the length of the lvl variable
length_lvl <- length(lvl)
print(length_lvl)

[1] 10


In [8]:
#Find the standard deviation of the values in lvl
sd_lvl <- sd(lvl)
print(sd_lvl)

[1] 4.022161


In [9]:
#Find the standard deviation of the elements in lvl, then round it; do it in a single command
rounded_sd_lvl <- round(sd(lvl))
print(rounded_sd_lvl)


[1] 4


In [10]:
#Find the standard deviation of the elements in lvl, then round it, then specifically ask R to print it; do it in a single command
print(round(sd(lvl)))

[1] 4


In [21]:
  x <- 1:12
  sample(x, 5, replace = FALSE)

[1]  9  2 11 12 10

In [22]:
# Find out what arguments the median function takes. While calling the median for the lvl object, try setting the na.rm = argument to TRUE.
median_lvl <- median(lvl, na.rm = TRUE)
print(median_lvl)


[1] 10


In [ ]:
# Does R return a different value from the one when na.rm = is set to FALSE (NB: the default value for the na.rm = argument is FALSE; this means that whenever we do not explicitly specify that it must be set to TRUE, it is set to FALSE?

# Yes, when the na.rm argument of a function in R is set to FALSE (which is the default value if not specified), it means that the function will not remove any missing values (NA) from the calculation.

In [25]:
atk <- c(3000, NA, NA, NA, NA, 4000, 3000, 5000, 1000, 5000)
median_lvl <- median(atk, na.rm = TRUE)
print(median_lvl)

[1] 3500


In [ ]:
# The output may be different from the median calculation without removing missing values. The reason is that when you include na.rm = TRUE, any missing values in the atk variable will be ignored, and the median will be calculated based on the non-missing values only.

In [32]:
draw <- function(){
    deck <- c("Duke", "Assassin", "Captain", "Ambassador", "Contessa")
    hand <- sample(deck, size=3, replace = T)
    return(hand)
    }
draw()

[1] "Duke"    "Captain" "Captain"

In [35]:
# Following the schema laid out there, write a function that flips a coin 100 times.
flip_coin <- function() {
  outcomes <- c("Heads", "Tails")
  flips <- sample(outcomes, size = 100, replace = T)
  return(flips)
}

flip_coin()

[1] "Tails" "Tails" "Heads" "Tails" "Heads" "Tails" "Tails" "Tails" "Tails"
 [10] "Heads" "Heads" "Tails" "Tails" "Heads" "Tails" "Heads" "Tails" "Tails"
 [19] "Heads" "Heads" "Heads" "Tails" "Heads" "Tails" "Tails" "Heads" "Heads"
 [28] "Heads" "Heads" "Heads" "Heads" "Tails" "Tails" "Heads" "Heads" "Heads"
 [37] "Heads" "Tails" "Tails" "Tails" "Tails" "Tails" "Tails" "Tails" "Tails"
 [46] "Heads" "Heads" "Tails" "Tails" "Heads" "Tails" "Tails" "Tails" "Tails"
 [55] "Heads" "Tails" "Tails" "Tails" "Tails" "Tails" "Tails" "Tails" "Heads"
 [64] "Heads" "Heads" "Heads" "Tails" "Tails" "Tails" "Heads" "Heads" "Tails"
 [73] "Heads" "Tails" "Heads" "Tails" "Heads" "Heads" "Heads" "Heads" "Tails"
 [82] "Tails" "Tails" "Heads" "Tails" "Tails" "Heads" "Tails" "Heads" "Heads"
 [91] "Tails" "Heads" "Heads" "Heads" "Heads" "Heads" "Tails" "Heads" "Tails"
[100] "Tails"

In [37]:
flip_coin <- function() {
  outcomes <- c("Heads", "Tails")
  flips <- sample(outcomes, size = 100, replace = T, prob = c(0.3, 0.7))
  return(flips)
}

flip_coin()

[1] "Tails" "Tails" "Tails" "Tails" "Tails" "Heads" "Tails" "Tails" "Tails"
 [10] "Heads" "Tails" "Heads" "Tails" "Heads" "Tails" "Tails" "Tails" "Tails"
 [19] "Tails" "Tails" "Tails" "Tails" "Tails" "Heads" "Tails" "Tails" "Heads"
 [28] "Heads" "Tails" "Heads" "Heads" "Heads" "Heads" "Heads" "Tails" "Heads"
 [37] "Tails" "Tails" "Tails" "Tails" "Heads" "Tails" "Tails" "Heads" "Tails"
 [46] "Tails" "Tails" "Tails" "Tails" "Heads" "Heads" "Tails" "Tails" "Tails"
 [55] "Tails" "Heads" "Tails" "Tails" "Tails" "Tails" "Tails" "Tails" "Tails"
 [64] "Heads" "Tails" "Tails" "Tails" "Tails" "Tails" "Heads" "Tails" "Heads"
 [73] "Heads" "Tails" "Heads" "Tails" "Heads" "Tails" "Tails" "Tails" "Tails"
 [82] "Heads" "Tails" "Tails" "Tails" "Tails" "Heads" "Heads" "Heads" "Tails"
 [91] "Tails" "Heads" "Tails" "Tails" "Tails" "Heads" "Heads" "Tails" "Tails"
[100] "Tails"

In [38]:
atk <- c(3000, NA, NA, NA, NA, 4000, 3000, 5000, 1000, 5000)

In [41]:
#The 6-th value (can you do it in more than one way)
sixth_value <- atk[6]
sixth_value

[1] 4000

In [42]:
#All the values but the 2nd one
values_except_second <- atk[-2]
values_except_second

[1] 3000   NA   NA   NA 4000 3000 5000 1000 5000

In [43]:
#Values 1, 3, 5, 7, and 9
values_1_3_5_7_9 <- atk[c(1, 3, 5, 7, 9)]
values_1_3_5_7_9

[1] 3000   NA   NA 3000 1000

In [44]:
#All the values but the 4th, 5th, and 6th
values_except_fourth_fifth_sixth <- atk[-c(4, 5, 6)]
values_except_fourth_fifth_sixth

[1] 3000   NA   NA 3000 5000 1000 5000

In [45]:
#All the values larger than 2000
values_larger_than_2000 <- atk[atk > 2000]
values_larger_than_2000

[1] 3000   NA   NA   NA   NA 4000 3000 5000 5000

In [46]:
weight <- c(71, 67, 83, 67)
height <- c(1.75, 1.81, 1.78, 1.82, 1.97, 2.12, 2.75)

bmi <- weight / height^2
print(bmi)

Warning message in weight/height^2:
"longer object length is not a multiple of shorter object length"


[1] 23.18367 20.45115 26.19619 20.22703 18.29473 14.90744 10.97521


In [47]:
weight <- c(71, 67, 83, 67)
height <- c(1.75, 1.81, 1.78, 1.82, 1.97, 2.12, 2.75)

recycled_weight <- rep(weight, length.out = length(height))
bmi <- recycled_weight / height^2

print(bmi)

[1] 23.18367 20.45115 26.19619 20.22703 18.29473 14.90744 10.97521


In [63]:
# Requirements: the following vectors: the original cards object, and atk from the second exercise.
atk <- c(3000, NA, NA, NA, NA, 4000, 3000, 5000, 1000, 5000)
cards <- c("Blue-Eyes White Dragon", "Exodius", "The Winged Dragon of Ra", "Raigeki", "Slifer the Sky Dragon", "Obelisk the Tormentor", "Black Luster Soldier", "5-Headed Dragon", "Exodia the Forbidden One", "Dragon Master Knight")

In [66]:
# Assign a name to each element from the atk vector that corresponds to a character from the cards vector.
names(atk) <- cards
atk

Blue-Eyes White Dragon                  Exodius  The Winged Dragon of Ra 
                    3000                       NA                       NA 
                 Raigeki    Slifer the Sky Dragon    Obelisk the Tormentor 
                      NA                       NA                     4000 
    Black Luster Soldier          5-Headed Dragon Exodia the Forbidden One 
                    3000                     5000                     1000 
    Dragon Master Knight 
                    5000

In [65]:
# Check the attributes of the atk element.
attributes(atk)

$names
 [1] "Blue-Eyes White Dragon"   "Exodius"                 
 [3] "The Winged Dragon of Ra"  "Raigeki"                 
 [5] "Slifer the Sky Dragon"    "Obelisk the Tormentor"   
 [7] "Black Luster Soldier"     "5-Headed Dragon"         
 [9] "Exodia the Forbidden One" "Dragon Master Knight"

In [56]:
# Is there another command you can use to check if the atk object has names assigned to it?
has_names <- !is.null(names(atk))
has_names

[1] TRUE


In [ ]:
# Remove the names.
names(atk) <- NULL

In [57]:
# Can you think of another way to assign names to the atk object?
atk <- c(3000, NA, NA, NA, NA, 4000, 3000, 5000, 1000, 5000)
cards <- c("Blue-Eyes White Dragon", "Exodius", "The Winged Dragon of Ra", "Raigeki", "Slifer the Sky Dragon", "Obelisk the Tormentor", "Black Luster Soldier", "5-Headed Dragon", "Exodia the Forbidden One", "Dragon Master Knight")

atk <- setNames(atk, cards)

In [58]:
atk

Blue-Eyes White Dragon                  Exodius  The Winged Dragon of Ra 
                    3000                       NA                       NA 
                 Raigeki    Slifer the Sky Dragon    Obelisk the Tormentor 
                      NA                       NA                     4000 
    Black Luster Soldier          5-Headed Dragon Exodia the Forbidden One 
                    3000                     5000                     1000 
    Dragon Master Knight 
                    5000

In [59]:
# Create a vector s that stores the number sequence 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30. Use the seq() command to do that.
s <- seq(from = 2, to = 30, by = 2)
s

 [1]  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30


In [61]:
# Check the attributes of s.
attributes(s)

NULL

In [ ]:
# Does it have any dimensions?
# No, the vector s does not have any dimensions. It is a one-dimensional vector with 15 elements. When you create a vector using the seq() function, it creates a one-dimensional vector by default.

In [67]:
# Give it dimensions. Try specifying 3 rows and 5 columns.
s <- seq(from = 2, to = 30, by = 2)
dim(s) <- c(3, 5)
s

     [,1] [,2] [,3] [,4] [,5]
[1,]    2    8   14   20   26
[2,]    4   10   16   22   28
[3,]    6   12   18   24   30


In [ ]:
# What happens if we try to go beyond the traditional height and width properties and specify a value for depth, too. Let's create a hypercube that has 1 row, 3 columns and 5 "slices".

In [79]:
# Try assigning the following dimensions to s: 1, 3, 5.
s <- seq(from = 2, to = 30, by = 2)
treedimensions <- array(s, dim = c(1, 3, 5))
print(treedimensions)

, , 1

     [,1] [,2] [,3]
[1,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   14   16   18

, , 4

     [,1] [,2] [,3]
[1,]   20   22   24

, , 5

     [,1] [,2] [,3]
[1,]   26   28   30



In [80]:
# Can you do more than that? Do you think this could be useful for something?
# Yes
s <- seq(from = 2, to = 30, by = 2)

fourdimensions <- array(s, dim = c(1, 3, 5, 2))
print(fourdimensions)

, , 1, 1

     [,1] [,2] [,3]
[1,]    2    4    6

, , 2, 1

     [,1] [,2] [,3]
[1,]    8   10   12

, , 3, 1

     [,1] [,2] [,3]
[1,]   14   16   18

, , 4, 1

     [,1] [,2] [,3]
[1,]   20   22   24

, , 5, 1

     [,1] [,2] [,3]
[1,]   26   28   30

, , 1, 2

     [,1] [,2] [,3]
[1,]    2    4    6

, , 2, 2

     [,1] [,2] [,3]
[1,]    8   10   12

, , 3, 2

     [,1] [,2] [,3]
[1,]   14   16   18

, , 4, 2

     [,1] [,2] [,3]
[1,]   20   22   24

, , 5, 2

     [,1] [,2] [,3]
[1,]   26   28   30



In [81]:
matrix_df <- data.frame(Player = c("dark", "dark", "dark", "dark", "dark", "light", "light", "light", "light", "light"),
                        Piece = c("king", "queen", "pawn", "pawn", "knight", "bishop", "king", "rook", "pawn", "pawn"))
print(matrix_df)

   Player  Piece
1    dark   king
2    dark  queen
3    dark   pawn
4    dark   pawn
5    dark knight
6   light bishop
7   light   king
8   light   rook
9   light   pawn
10  light   pawn


In [82]:
matrix_mat <- matrix(c("dark", "dark", "dark", "dark", "dark", "light", "light", "light", "light", "light",
                       "king", "queen", "pawn", "pawn", "knight", "bishop", "king", "rook", "pawn", "pawn"),
                     ncol = 2, byrow = TRUE)
print(matrix_mat)

      [,1]     [,2]    
 [1,] "dark"   "dark"  
 [2,] "dark"   "dark"  
 [3,] "dark"   "light" 
 [4,] "light"  "light" 
 [5,] "light"  "light" 
 [6,] "king"   "queen" 
 [7,] "pawn"   "pawn"  
 [8,] "knight" "bishop"
 [9,] "king"   "rook"  
[10,] "pawn"   "pawn"  


In [83]:
player <- c("dark", "dark", "dark", "dark", "dark", "light", "light", "light", "light", "light")
piece <- c("king", "queen", "pawn", "pawn", "knight", "bishop", "king", "rook", "pawn", "pawn")

matrix_mat <- cbind(player, piece)
dim(matrix_mat) <- c(10, 2)

print(matrix_mat)

      [,1]    [,2]    
 [1,] "dark"  "king"  
 [2,] "dark"  "queen" 
 [3,] "dark"  "pawn"  
 [4,] "dark"  "pawn"  
 [5,] "dark"  "knight"
 [6,] "light" "bishop"
 [7,] "light" "king"  
 [8,] "light" "rook"  
 [9,] "light" "pawn"  
[10,] "light" "pawn"  


In [84]:
player_piece <- c("dark", "king", "dark", "queen", "dark", "pawn", "dark", "pawn", "dark", "knight", "light", "bishop", "light", "king", "light", "rook", "light", "pawn", "light", "pawn")
matrix_mat <- matrix(player_piece, ncol = 2, byrow = TRUE)

print(matrix_mat)

      [,1]    [,2]    
 [1,] "dark"  "king"  
 [2,] "dark"  "queen" 
 [3,] "dark"  "pawn"  
 [4,] "dark"  "pawn"  
 [5,] "dark"  "knight"
 [6,] "light" "bishop"
 [7,] "light" "king"  
 [8,] "light" "rook"  
 [9,] "light" "pawn"  
[10,] "light" "pawn"  


In [85]:
player_piece <- c("dark", "king", "dark", "queen", "dark", "pawn", "dark", "pawn", "dark", "knight", "light", "bishop", "light", "king", "light", "rook", "light", "pawn", "light", "pawn")
matrix_mat <- matrix(player_piece, ncol = 2, byrow = TRUE)
dimnames(matrix_mat) <- list(NULL, c("Player", "Piece"))

print(matrix_mat)


      Player  Piece   
 [1,] "dark"  "king"  
 [2,] "dark"  "queen" 
 [3,] "dark"  "pawn"  
 [4,] "dark"  "pawn"  
 [5,] "dark"  "knight"
 [6,] "light" "bishop"
 [7,] "light" "king"  
 [8,] "light" "rook"  
 [9,] "light" "pawn"  
[10,] "light" "pawn"  


In [86]:
player_piece <- c("dark", "king", "dark", "queen", "dark", "pawn", "dark", "pawn", "dark", "knight", "light", "bishop", "light", "king", "light", "rook", "light", "pawn", "light", "pawn")
matrix_mat <- matrix(player_piece, ncol = 2, byrow = TRUE)
colnames(matrix_mat) <- c("Player", "Piece")
rownames(matrix_mat) <- 1:nrow(matrix_mat)

print(matrix_mat)


   Player  Piece   
1  "dark"  "king"  
2  "dark"  "queen" 
3  "dark"  "pawn"  
4  "dark"  "pawn"  
5  "dark"  "knight"
6  "light" "bishop"
7  "light" "king"  
8  "light" "rook"  
9  "light" "pawn"  
10 "light" "pawn"  


In [87]:
player_piece <- c("dark", "king", "dark", "queen", "dark", "pawn", "dark", "pawn", "dark", "knight", "light", "bishop", "light", "king", "light", "rook", "light", "pawn", "light", "pawn")
matrix_mat <- matrix(player_piece, ncol = 2, byrow = TRUE)

names_mat <- matrix(c("Player", "Piece"), ncol = 2, dimnames = list(NULL, c("Player", "Piece")))

matrix_with_names <- rbind(names_mat, matrix_mat)

print(matrix_with_names)


      Player   Piece   
 [1,] "Player" "Piece" 
 [2,] "dark"   "king"  
 [3,] "dark"   "queen" 
 [4,] "dark"   "pawn"  
 [5,] "dark"   "pawn"  
 [6,] "dark"   "knight"
 [7,] "light"  "bishop"
 [8,] "light"  "king"  
 [9,] "light"  "rook"  
[10,] "light"  "pawn"  
[11,] "light"  "pawn"  


In [89]:
add_row <- function(matrix_mat) {
  player <- readline("Enter player: ")
  piece <- readline("Enter piece: ")
  new_row <- c(player, piece)
  matrix_mat <- rbind(matrix_mat, new_row)
  return(matrix_mat)
}

# Example usage
matrix_mat <- matrix(c("dark", "king", "dark", "queen", "dark", "pawn", "dark", "pawn", "dark", "knight", "light", "bishop", "light", "king", "light", "rook", "light", "pawn", "light", "pawn"), ncol = 2, byrow = TRUE)
print(matrix_mat)

      [,1]    [,2]    
 [1,] "dark"  "king"  
 [2,] "dark"  "queen" 
 [3,] "dark"  "pawn"  
 [4,] "dark"  "pawn"  
 [5,] "dark"  "knight"
 [6,] "light" "bishop"
 [7,] "light" "king"  
 [8,] "light" "rook"  
 [9,] "light" "pawn"  
[10,] "light" "pawn"  


In [90]:
matrix_mat <- add_row(matrix_mat)
print(matrix_mat)

        [,1]    [,2]    
        "dark"  "king"  
        "dark"  "queen" 
        "dark"  "pawn"  
        "dark"  "pawn"  
        "dark"  "knight"
        "light" "bishop"
        "light" "king"  
        "light" "rook"  
        "light" "pawn"  
        "light" "pawn"  
new_row ""      ""      
