In [3]:
# Pictured below is a matrix. Recreate this matrix in at least three different ways. 

#Player  Piece   
#[1,] "dark"  "king"  
#[2,] "dark"  "queen" 
#[3,] "dark"  "pawn"  
#[4,] "dark"  "pawn"  
#[5,] "dark"  "knight"
#[6,] "light" "bishop"
#[7,] "light" "king"  
#[8,] "light" "rook"  
#[9,] "light" "pawn"  
#[10,] "light" "pawn"  

matrix_data <- matrix(c("dark", "dark", "dark", "dark", "dark", "light", "light", "light", "light", "light", "king", "queen", "pawn", "pawn", "knight", "bishop", "king", "rook", "pawn", "pawn"), nrow = 10, byrow = TRUE)

In [4]:
matrix_data

[,1]   [,2]  
 [1,] dark   dark  
 [2,] dark   dark  
 [3,] dark   light 
 [4,] light  light 
 [5,] light  light 
 [6,] king   queen 
 [7,] pawn   pawn  
 [8,] knight bishop
 [9,] king   rook  
[10,] pawn   pawn

In [5]:
# # Use the cbind() function
col1 <- c("dark", "dark", "dark", "dark", "dark", "light", "light", "light", "light", "light")
col2 <- c("king", "queen", "pawn", "pawn", "knight", "bishop", "king", "rook", "pawn", "pawn")
matrix_data <- cbind(col1, col2)
matrix_data

col1  col2  
 [1,] dark  king  
 [2,] dark  queen 
 [3,] dark  pawn  
 [4,] dark  pawn  
 [5,] dark  knight
 [6,] light bishop
 [7,] light king  
 [8,] light rook  
 [9,] light pawn  
[10,] light pawn

In [6]:
# Use the dim() function
matrix_data <- c("dark", "dark", "dark", "dark", "dark", "light", "light", "light", "light", "light",
                 "king", "queen", "pawn", "pawn", "knight", "bishop", "king", "rook", "pawn", "pawn")
dim(matrix_data) <- c(10, 2)
matrix_data

[,1]  [,2]  
 [1,] dark  king  
 [2,] dark  queen 
 [3,] dark  pawn  
 [4,] dark  pawn  
 [5,] dark  knight
 [6,] light bishop
 [7,] light king  
 [8,] light rook  
 [9,] light pawn  
[10,] light pawn

In [7]:
# Can you think of a faster way to create this matrix?
matrix_data <- data.frame(
    Player = c("dark", "dark", "dark", "dark", "dark", "light", "light", "light", "light", "light"),
    Piece = c("king", "queen", "pawn", "pawn", "knight", "bishop", "king", "rook", "pawn", "pawn")
)
matrix_data

Player Piece 
1  dark   king  
2  dark   queen 
3  dark   pawn  
4  dark   pawn  
5  dark   knight
6  light  bishop
7  light  king  
8  light  rook  
9  light  pawn  
10 light  pawn

In [8]:
# Assign names to it in two different ways.
# 1
matrix_data <- matrix(c("dark", "dark", "dark", "dark", "dark", "light", "light", "light", "light", "light",
                        "king", "queen", "pawn", "pawn", "knight", "bishop", "king", "rook", "pawn", "pawn"),
                      nrow = 10, byrow = TRUE)

rownames(matrix_data) <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10")
colnames(matrix_data) <- c("Player", "Piece")

matrix_data

Player Piece 
1  dark   dark  
2  dark   dark  
3  dark   light 
4  light  light 
5  light  light 
6  king   queen 
7  pawn   pawn  
8  knight bishop
9  king   rook  
10 pawn   pawn

In [9]:
# 2
matrix_data <- matrix(c("dark", "dark", "dark", "dark", "dark", "light", "light", "light", "light", "light",
                        "king", "queen", "pawn", "pawn", "knight", "bishop", "king", "rook", "pawn", "pawn"),
                      nrow = 10, byrow = TRUE)

dimnames(matrix_data) <- list(c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10"), c("Player", "Piece"))
matrix_data

Player Piece 
1  dark   dark  
2  dark   dark  
3  dark   light 
4  light  light 
5  light  light 
6  king   queen 
7  pawn   pawn  
8  knight bishop
9  king   rook  
10 pawn   pawn

In [10]:
# Would using rbind() be practical in this case?
# Using rbind() to add rows to the matrix would not be practical in this case 
# because rbind() is used to combine matrices with the same number of columns. 
# Since the original matrix has 2 columns and the rows you want to add would have more than 2 columns, rbind() would not work.

In [11]:
# Can you think of a way to make adding a row to the matrix worthwhile?
new_row <- data.frame(
  Player = "dark",
  Piece = "queen"
)

matrix_data <- rbind(matrix_data, new_row)
matrix_data

Player Piece 
1  dark   dark  
2  dark   dark  
3  dark   light 
4  light  light 
5  light  light 
6  king   queen 
7  pawn   pawn  
8  knight bishop
9  king   rook  
10 pawn   pawn  
11 dark   queen

In [12]:
matrix_data <- data.frame(
    Player = c("dark", "dark", "dark", "dark", "dark", "light", "light", "light", "light", "light"),
    Piece = c("king", "queen", "pawn", "pawn", "knight", "bishop", "king", "rook", "pawn", "pawn")
)
# Transpose the matrix
transposed_matrix <- t(matrix_data)

# Create a new row with the values
new_row <- c(3, 5, 2, 2, 7, 4, 6, 5, 2, 1)

# Add the new row to the transposed matrix
final_matrix <- rbind(transposed_matrix, new_row)
final_matrix

[,1] [,2]  [,3] [,4] [,5]   [,6]   [,7]  [,8]  [,9]  [,10]
Player  dark dark  dark dark dark   light  light light light light
Piece   king queen pawn pawn knight bishop king  rook  pawn  pawn 
new_row 3    5     2    2    7      4      6     5     2     1

In [13]:
# Name the row "Turn" and transpose the matrix back to its original orientation.
# Name the new_row as "Turn"
rownames(final_matrix)[rownames(final_matrix) == "new_row"] <- "Turn"
final_matrix

[,1] [,2]  [,3] [,4] [,5]   [,6]   [,7]  [,8]  [,9]  [,10]
Player dark dark  dark dark dark   light  light light light light
Piece  king queen pawn pawn knight bishop king  rook  pawn  pawn 
Turn   3    5     2    2    7      4      6     5     2     1

In [33]:
# Transpose the matrix back to its original orientation
original_matrix <- t(final_matrix)
# Rename
cmatrix <- original_matrix
cmatrix

Player Piece  Turn
 [1,] dark   king   3   
 [2,] dark   queen  5   
 [3,] dark   pawn   2   
 [4,] dark   pawn   2   
 [5,] dark   knight 7   
 [6,] light  bishop 4   
 [7,] light  king   6   
 [8,] light  rook   5   
 [9,] light  pawn   2   
[10,] light  pawn   1

In [31]:
# Extract the following values from the chess matrix:
#The first piece of the light player
first_light_piece <- cmatrix[cmatrix[, "Player"] == "light", "Piece"][1]
first_light_piece

[1] "bishop"

In [37]:
#The Player and Piece columns
player_piece <- cmatrix[, c("Player", "Piece")]
player_piece

Player Piece 
 [1,] dark   king  
 [2,] dark   queen 
 [3,] dark   pawn  
 [4,] dark   pawn  
 [5,] dark   knight
 [6,] light  bishop
 [7,] light  king  
 [8,] light  rook  
 [9,] light  pawn  
[10,] light  pawn

In [39]:
#All the information about the dark player
dark_player <- cmatrix[cmatrix[, "Player"] == "dark", ]
dark_player

Player Piece  Turn
[1,] dark   king   3   
[2,] dark   queen  5   
[3,] dark   pawn   2   
[4,] dark   pawn   2   
[5,] dark   knight 7

In [41]:
#The Pieces column; try to extract that as a matrix (Hint: lookup the drop = argument)
pieces_matrix <- cmatrix[, "Piece", drop = FALSE]
pieces_matrix

Piece 
 [1,] king  
 [2,] queen 
 [3,] pawn  
 [4,] pawn  
 [5,] knight
 [6,] bishop
 [7,] king  
 [8,] rook  
 [9,] pawn  
[10,] pawn

In [46]:
#Everything but the Piece column
everything_but_piece <- cmatrix[, -which(colnames(cmatrix) == "Piece")]
everything_but_piece

Player Turn
 [1,] dark   3   
 [2,] dark   5   
 [3,] dark   2   
 [4,] dark   2   
 [5,] dark   7   
 [6,] light  4   
 [7,] light  6   
 [8,] light  5   
 [9,] light  2   
[10,] light  1

In [47]:
#The 1st and 3rd values on the second row
values_second_row <- cmatrix[2, c(1, 3)]
values_second_row

Player   Turn 
"dark"    "5"

In [48]:
#Replace the 3rd value on the 7th row with 3 (Hint: works just like creating an object)
cmatrix[7, 3] <- 3
cmatrix

Player Piece  Turn
 [1,] dark   king   3   
 [2,] dark   queen  5   
 [3,] dark   pawn   2   
 [4,] dark   pawn   2   
 [5,] dark   knight 7   
 [6,] light  bishop 4   
 [7,] light  king   3   
 [8,] light  rook   5   
 [9,] light  pawn   2   
[10,] light  pawn   1

In [50]:
# Lookup the runif() function. Create a 3x4 matrix with 12 random numbers generated using the runif() function; have the matrix be filled our row-by-row, instead of column-by-column.
random_matrix <- matrix(runif(12), nrow = 3, ncol = 4, byrow = TRUE)
random_matrix

[,1]      [,2]       [,3]      [,4]      
[1,] 0.9279831 0.84924369 0.2769278 0.70465869
[2,] 0.4225895 0.13913406 0.6978044 0.04050674
[3,] 0.5543263 0.03739122 0.1790024 0.20781976

In [52]:
# Name the columns of the matrix uno, dos, tres, cuatro, and the rows x, y, z.
colnames(random_matrix) <- c("uno", "dos", "tres", "cuatro")
rownames(random_matrix) <- c("x", "y", "z")
random_matrix

uno       dos        tres      cuatro    
x 0.9279831 0.84924369 0.2769278 0.70465869
y 0.4225895 0.13913406 0.6978044 0.04050674
z 0.5543263 0.03739122 0.1790024 0.20781976

In [53]:
# Scale the matrix by 10 and save the result.
scaled_matrix <- random_matrix * 10
scaled_matrix

uno      dos       tres     cuatro   
x 9.279831 8.4924369 2.769278 7.0465869
y 4.225895 1.3913406 6.978044 0.4050674
z 5.543263 0.3739122 1.790024 2.0781976

In [54]:
# Extract a 2x4 matrix from it and save the result.
extracted_matrix <- scaled_matrix[1:2, ]
extracted_matrix

uno      dos      tres     cuatro   
x 9.279831 8.492437 2.769278 7.0465869
y 4.225895 1.391341 6.978044 0.4050674

In [56]:
# Subtract the smaller matrix from the larger one. Can you do that? Why?
# The subtraction operation between scaled_matrix and extracted_matrix is not possible because they have different dimensions.

In [59]:
# Extract a 3x3 matrix from the original matrix and save the result. Try the subtraction again. Can you do that? Why?
extracted_matrix_2 <- random_matrix[1:3, ]
extracted_matrix_2
  # The subtraction between the extracted 3x3 matrix and the scaled matrix can be performed since they have the same dimensions.

uno       dos        tres      cuatro    
x 0.9279831 0.84924369 0.2769278 0.70465869
y 0.4225895 0.13913406 0.6978044 0.04050674
z 0.5543263 0.03739122 0.1790024 0.20781976

In [62]:
# Extract the column called "uno" as a vector from the original matrix and save the result. Try the subtraction again. Can you do that? Why?
column_uno <- random_matrix[, "uno"]
column_uno
  # The column vector has the same number of rows as the scaled matrix, the subtraction is possible.

x         y         z 
0.9279831 0.4225895 0.5543263

In [64]:
# Lookup the rnorm() function. Create a new 3x4 matrix with 12 random values generated using the rnorm() function.
new_matrix <- matrix(rnorm(12), nrow = 3, ncol = 4)
new_matrix

[,1]       [,2]       [,3]       [,4]     
[1,]  0.7403804 -0.0323787 -0.4113426 0.1346450
[2,] -1.1124802  1.5756257  1.3755943 0.8051033
[3,]  0.9204097 -1.6155587  0.1363537 1.5335324

In [66]:
# Perform matrix multiplication (using the * sign). Can you do that? How is the operation carried out?
# No. The dimensions of the two matrix are not compatible.

In [68]:
# Perform inner matrix multiplication with the two matrixes. Can you do that? Why? Can you think of something to do to make this possible?
# No. The dimensions of the two matrix are not compatible.

In [70]:
# transposes random_matrix to matches the number of rows in new_matrix
inner_matrix_multiplication <- t(random_matrix) %*% new_matrix
inner_matrix_multiplication

[,1]       [,2]       [,3]       [,4]     
uno     0.7271453 -0.2597506  0.2751772 1.3152537
dos     0.5083948  0.1313181 -0.1528396 0.2837043
tres   -0.4065061  0.8013230  0.8703912 0.8735975
cuatro  0.6679319 -0.2947375 -0.2057983 0.4461892

In [71]:
# Create a 5x5 matrix with the rnorm() function, and a 5x5 matrix with runif(). Create each in a single line of code (Hint: nest the operations)
normal_matrix <- matrix(rnorm(25), nrow = 5, ncol = 5)
uniform_matrix <- matrix(runif(25), nrow = 5, ncol = 5)

In [72]:
normal_matrix

[,1]       [,2]        [,3]       [,4]       [,5]       
[1,]  0.9975260 -0.04445931 -2.3090183 -2.8330340  0.06726294
[2,] -0.1325227  0.27521502 -0.3771561  0.1901322 -1.23380748
[3,] -0.5896622  0.41422142 -1.9077864  0.2241095  1.34806413
[4,] -0.3072546  0.29349028  0.2655817  2.6748842  0.51505037
[5,] -1.4946115 -0.12044043 -0.2550777 -0.3054737  0.29541804

In [73]:
uniform_matrix

[,1]       [,2]       [,3]       [,4]      [,5]     
[1,] 0.28962906 0.89899637 0.75148415 0.2111072 0.5076940
[2,] 0.23719236 0.04091437 0.02927448 0.2972380 0.6819853
[3,] 0.06286468 0.95030242 0.88739601 0.7611523 0.8016790
[4,] 0.40653897 0.98694777 0.59067476 0.4477037 0.8969843
[5,] 0.42732841 0.58701430 0.48297712 0.8413435 0.5851025

In [84]:
# For the two matrices, get the following information; for the first four, save the new values as columns in their corresponding matrixes:
# Column averages
normal_column_averages <- colMeans(normal_matrix)
uniform_column_averages <- colMeans(uniform_matrix)

In [85]:
normal_column_averages

[1] -0.305305006  0.163605396 -0.916691373 -0.009876371  0.198397600

In [86]:
uniform_column_averages

[1] 0.2847107 0.6928350 0.5483613 0.5117089 0.6946890

In [77]:
# Row averages
normal_row_averages <- rowMeans(normal_matrix)
uniform_row_averages <- rowMeans(uniform_matrix)

In [87]:
normal_row_averages

[1] -0.8243445 -0.2556278 -0.1022107  0.6883504 -0.3760371

In [88]:
uniform_row_averages

[1] 0.5317822 0.2573209 0.6926789 0.6657699 0.5847532

In [78]:
# Column sums
normal_column_sums <- colSums(normal_matrix)
uniform_column_sums <- colSums(uniform_matrix)

In [89]:
normal_column_sums

[1] -1.52652503  0.81802698 -4.58345687 -0.04938185  0.99198800

In [90]:
uniform_column_sums

[1] 1.423553 3.464175 2.741807 2.558545 3.473445

In [79]:
# Row sums
normal_row_sums <- rowSums(normal_matrix)
uniform_row_sums <- rowSums(uniform_matrix)

In [91]:
normal_row_sums

[1] -4.1217227 -1.2781391 -0.5110536  3.4417520 -1.8801853

In [92]:
uniform_row_sums

[1] 2.658911 1.286604 3.463394 3.328850 2.923766

In [80]:
# Minimum and maximum value in the matrix
normal_min_value <- min(normal_matrix)
normal_max_value <- max(normal_matrix)
uniform_min_value <- min(uniform_matrix)
uniform_max_value <- max(uniform_matrix)

In [81]:
# Minimum and maximum value for the 3rd column in each matrix
normal_column_3_min <- min(normal_matrix[, 3])
normal_column_3_max <- max(normal_matrix[, 3])
uniform_column_3_min <- min(uniform_matrix[, 3])
uniform_column_3_max <- max(uniform_matrix[, 3])

In [93]:
# Requirements: the chess matrix from Exercise 11.
cmatrix

Player Piece  Turn
 [1,] dark   king   3   
 [2,] dark   queen  5   
 [3,] dark   pawn   2   
 [4,] dark   pawn   2   
 [5,] dark   knight 7   
 [6,] light  bishop 4   
 [7,] light  king   3   
 [8,] light  rook   5   
 [9,] light  pawn   2   
[10,] light  pawn   1

In [105]:
# Save the Piece column of the matrix as a vector.
piece_vector <- cmatrix[, "Piece"]
piece_vector

[1] "king"   "queen"  "pawn"   "pawn"   "knight" "bishop" "king"   "rook"  
 [9] "pawn"   "pawn"

In [122]:
# Create a factor from the vector
piece_factor <- factor(piece_vector)
piece_factor

[1] king   queen  pawn   pawn   knight bishop king   rook   pawn   pawn  
Levels: bishop king knight pawn queen rook

In [123]:
# Organize the levels in the following : King, Queen, Rook, Bishop, Knight, Pawn.
# Rename the levels
levels(piece_factor) <- c("King", "Queen", "Rook", "Bishop", "Knight", "Pawn")
piece_factor <- factor(piece_factor, levels = c("King", "Queen", "Rook", "Bishop", "Knight", "Pawn"))
piece_factor

[1] Queen  Knight Bishop Bishop Rook   King   Queen  Pawn   Bishop Bishop
Levels: King Queen Rook Bishop Knight Pawn

In [124]:
# Rename the levels with their initial letters
levels(piece_factor) <- substr(levels(piece_factor), 1, 1)

In [125]:
# Save the Piece column of the matrix as a vector.
piece_factor <- factor(piece_factor, levels = c("K", "Q", "R", "B", "N", "P"))

In [126]:
piece_factor

[1] Q K B B R K Q P B B
Levels: K Q R B N P

In [151]:
# create a list which prints like this: 

# [[1]]
# [1]  1  3  5  7  9 11
#
# [[2]]
# [[2]][[1]]
# [1] "Happy Birthday"
#
# [[2]][[2]]
# [1] "Archery" 

# Create the list
my_list <- list(
  c(1, 3, 5, 7, 9, 11),
  list("Happy Birthday", "Archery")
)

# Print the list
print(my_list)

[[1]]
[1]  1  3  5  7  9 11

[[2]]
[[2]][[1]]
[1] "Happy Birthday"

[[2]][[2]]
[1] "Archery"




In [128]:
# Extract the numbers as a vector
numbers_vector <- my_list[[1]]
numbers_vector

[1]  1  3  5  7  9 11

In [129]:
# Extract the phrase "Happy Birthday" as a vector
phrase_vector <- my_list[[2]][[1]]
phrase_vector

[1] "Happy Birthday"

In [130]:
# Extract the second item of the second list as a list
second_item_list <- my_list[[2]][[2]]
second_item_list

[1] "Archery"

In [131]:
# Extract the second list as a list
second_list <- my_list[[2]]
second_list

[[1]]
[1] "Happy Birthday"

[[2]]
[1] "Archery"

In [132]:
# Extract the numbers item as a list
numbers_list <- list(Numbers = my_list[[1]])
numbers_list

$Numbers
[1]  1  3  5  7  9 11

In [136]:
# Add 2 to each element in the numbers item
numbers_vector <- numbers_vector + 2
numbers_vector

[1]  3  5  7  9 11 13

In [152]:
# Name the items in the list as "Numbers" and "Phrases"
names(my_list) <- c("Numbers", "Phrases")
my_list

$Numbers
[1]  1  3  5  7  9 11

$Phrases
$Phrases[[1]]
[1] "Happy Birthday"

$Phrases[[2]]
[1] "Archery"

In [138]:
# extract the numbers item from newList with the $
numbers_vector <- my_list$Numbers
numbers_vector

[1]  1  3  5  7  9 11

In [139]:
numbers_vector <- my_list$Phrases
numbers_vector

[[1]]
[1] "Happy Birthday"

[[2]]
[1] "Archery"

In [141]:
# The equivalent extract method
numbers_vector <- my_list[[1]]
numbers_vector

[1]  1  3  5  7  9 11

In [142]:
numbers_vector <- my_list[[2]]
numbers_vector

[[1]]
[1] "Happy Birthday"

[[2]]
[1] "Archery"

In [153]:
# Add a new item called "Brands" to the list
my_list$Brands <- c("Kellogs", "Nike", "iPhone")

In [154]:
my_list

$Numbers
[1]  1  3  5  7  9 11

$Phrases
$Phrases[[1]]
[1] "Happy Birthday"

$Phrases[[2]]
[1] "Archery"


$Brands
[1] "Kellogs" "Nike"    "iPhone"

In [156]:
# Remove "iPhone" from the "Brands" item
my_list$Brands <- my_list$Brands[my_list$Brands != "iPhone"]
my_list

$Numbers
[1]  1  3  5  7  9 11

$Phrases
$Phrases[[1]]
[1] "Happy Birthday"

$Phrases[[2]]
[1] "Archery"


$Brands
[1] "Kellogs" "Nike"

In [158]:
# Remove the "Brands" item from the list
my_list$Brands <- NULL
my_list

$Numbers
[1]  1  3  5  7  9 11

$Phrases
$Phrases[[1]]
[1] "Happy Birthday"

$Phrases[[2]]
[1] "Archery"